name: Deploy wholesale-needs-approval

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/wholesale-needs-approval/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add droplet to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.DROPLET_HOST }}" >> ~/.ssh/known_hosts

      - name: Rsync app to droplet
        run: |
          rsync -az --delete \
            --exclude=".git" \
            --exclude="node_modules" \
            ./apps/wholesale-needs-approval/ \
            ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}:${{ secrets.REMOTE_DIR }}/wholesale-needs-approval/

      - name: Write per-app .env from secret
        run: |
          ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} \
          "mkdir -p ${SECRET_REMOTE_DIR:-${{ secrets.REMOTE_DIR }}/wholesale-needs-approval} && \
           echo '${{ secrets.ENV_FILE }}' > ${SECRET_REMOTE_DIR:-${{ secrets.REMOTE_DIR }}/wholesale-needs-approval}/.env"

      - name: Install & reload with PM2
        run: |
          ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} \
          "set -euo pipefail; \
           source ~/.profile; \
           cd '${{ secrets.REMOTE_DIR }}/wholesale-needs-approval'; \
           npm ci; \
           pm2 reload wholesale-needs-approval --update-env || pm2 start index.js --name wholesale-needs-approval; \
           pm2 save"