name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add droplet host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H -p 22 ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure remote directory exists
        run: ssh "${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}" "mkdir -p '${{ secrets.REMOTE_DIR }}' '${{ secrets.REMOTE_DIR }}/data'"

      - name: Rsync repo to droplet (preserve server data/)
        run: |
          rsync -az --delete \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'data/' \
            ./  "${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}:${{ secrets.REMOTE_DIR }}/"

      # Create a temp .env on the runner from the secret (NOT committed), then upload it
      - name: Prepare .env from ENV_FILE (runner only)
        run: |
          printf "%s" "${{ secrets.ENV_FILE }}" > .env.deploy

      - name: Upload .env to server
        run: |
          scp .env.deploy "${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}:${{ secrets.REMOTE_DIR }}/.env"
          rm -f .env.deploy

      - name: Install deps & (re)start with PM2
        run: |
          ssh "${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}" bash -lc 'cat >/tmp/deploy_app.sh << "SCRIPT"
          set -euo pipefail
          APP_DIR="${{ secrets.REMOTE_DIR }}"
          APP_NAME="${{ secrets.APP_NAME }}"
          APP_DIR="${APP_DIR%/}"

          if [ -f ~/.profile ]; then . ~/.profile; fi
          if [ -f ~/.bashrc ]; then . ~/.bashrc; fi
          if [ -f ~/.nvm/nvm.sh ]; then . ~/.nvm/nvm.sh; fi

          if [ -z "$APP_DIR" ] || [ ! -d "$APP_DIR" ]; then echo "APP_DIR invalid: $APP_DIR" >&2; exit 2; fi
          if [ -z "$APP_NAME" ]; then APP_NAME="$(basename "$APP_DIR")"; fi
          if [ -z "$APP_NAME" ]; then echo "APP_NAME empty" >&2; exit 3; fi

          echo "APP_DIR=$APP_DIR"
          echo "APP_NAME=$APP_NAME"
          ls -la "$APP_DIR"

          if [ ! -f "$APP_DIR/.env" ]; then echo ".env missing in $APP_DIR" >&2; exit 4; fi

          cd "$APP_DIR"
          export NPM_CONFIG_FUND=false
          if [ ! -f package-lock.json ]; then npm install --package-lock-only; fi

          npm ci --omit=dev 2>/dev/null || npm ci --only=production 2>/dev/null || npm ci

          if ! command -v pm2 >/dev/null 2>&1; then npm i -g pm2 >/dev/null 2>&1 || npm i -g pm2; fi
          PM2_PATH="$(command -v pm2 || true)"
          if [ -z "$PM2_PATH" ]; then echo "pm2 not found after install" >&2; exit 5; fi
          echo "Using PM2 at: $PM2_PATH"

          TMP_PM2="/tmp/pm2_list.json"
          if ! "$PM2_PATH" jlist >"$TMP_PM2" 2>/dev/null; then echo "[]">$TMP_PM2; fi
          if grep -q "\"name\":\"$APP_NAME\"" "$TMP_PM2"; then
            "$PM2_PATH" reload "$APP_NAME" --update-env
          else
            "$PM2_PATH" start index.js --name "$APP_NAME" --cwd "$APP_DIR"
          fi

          "$PM2_PATH" save
          SCRIPT
          sed -i "s/\r$//" /tmp/deploy_app.sh
          # Uncomment the next line once if you want to see the exact script with line numbers:
          # nl -ba /tmp/deploy_app.sh | sed -n "1,200p"
          bash /tmp/deploy_app.sh
          '